#### Visualizing a Decision Tree

> Importing Data

In [58]:
import numpy as np
from sklearn.datasets import load_iris
from sklearn import tree
from sklearn.externals.six import StringIO
import pydot
iris = load_iris()
print iris.feature_names
#print iris.target_names
#print iris.data[0]
#print iris.target[0]
for i in range(len(iris.target)):
    print "Features: %d \t %s \t %s" % (i, iris.data[i], iris.target[i])

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
Features: 0 	 [ 5.1  3.5  1.4  0.2] 	 0
Features: 1 	 [ 4.9  3.   1.4  0.2] 	 0
Features: 2 	 [ 4.7  3.2  1.3  0.2] 	 0
Features: 3 	 [ 4.6  3.1  1.5  0.2] 	 0
Features: 4 	 [ 5.   3.6  1.4  0.2] 	 0
Features: 5 	 [ 5.4  3.9  1.7  0.4] 	 0
Features: 6 	 [ 4.6  3.4  1.4  0.3] 	 0
Features: 7 	 [ 5.   3.4  1.5  0.2] 	 0
Features: 8 	 [ 4.4  2.9  1.4  0.2] 	 0
Features: 9 	 [ 4.9  3.1  1.5  0.1] 	 0
Features: 10 	 [ 5.4  3.7  1.5  0.2] 	 0
Features: 11 	 [ 4.8  3.4  1.6  0.2] 	 0
Features: 12 	 [ 4.8  3.   1.4  0.1] 	 0
Features: 13 	 [ 4.3  3.   1.1  0.1] 	 0
Features: 14 	 [ 5.8  4.   1.2  0.2] 	 0
Features: 15 	 [ 5.7  4.4  1.5  0.4] 	 0
Features: 16 	 [ 5.4  3.9  1.3  0.4] 	 0
Features: 17 	 [ 5.1  3.5  1.4  0.3] 	 0
Features: 18 	 [ 5.7  3.8  1.7  0.3] 	 0
Features: 19 	 [ 5.1  3.8  1.5  0.3] 	 0
Features: 20 	 [ 5.4  3.4  1.7  0.2] 	 0
Features: 21 	 [ 5.1  3.7  1.5  0.4] 	 0
Features: 22 	 [ 4.6  3.6

> Training a Classifier
  - Need test data to test accuracy of classifier

In [59]:
test_idx = [0, 50, 100]

# training data
train_target = np.delete(iris.target, test_idx)
train_data = np.delete(iris.data, test_idx, axis = 0)

# testing data
test_target = iris.target[test_idx]
test_data = iris.data[test_idx]

clf = tree.DecisionTreeClassifier()
clf.fit(train_data, train_target)

print test_target
print clf.predict(test_data)

[0 1 2]
[0 1 2]


> Predict Label for New flower

- Write to PDF

In [60]:
dot_data = StringIO()
tree.export_graphviz(clf, out_file=dot_data, 
                         feature_names=iris.feature_names,  
                         class_names=iris.target_names,  
                         filled=True, rounded=True,  
                         impurity=False)
graph = pydot.graph_from_dot_data(dot_data.getvalue())
graph[0].write_pdf("iris.pdf")

print test_data[0], test_target[0]

print iris.feature_names, iris.target_names

[ 5.1  3.5  1.4  0.2] 0
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)'] ['setosa' 'versicolor' 'virginica']
